<?php
$z[0]=Array("arcurl","",32,47);
$z[1]=Array("litpic","",89,104);
$z[2]=Array("arcurl","",160,175);
$z[3]=Array("title","",200,214);
$z[4]=Array("title","",216,230);
$z[5]=Array("pubdate"," \$today = Floor(time()/(3600 * 24)); \$senday= Floor(@me/(3600 * 24)); \$updays = \$today-\$senday; if(\$updays==0) @me = \"今日\"; else @me = \$updays.\"天前\"; ",282,482);
$z[5][4]['runphp']="yes";
$z[6]=Array("click","",553,567);

?>