<?php
$z[0]=Array("global","",94,123);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",228,257);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("channel","\n            <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\n            ",494,714);
$z[2][4]['type']="top";
$z[2][4]['currentstyle']="<li class='active'><a href='~typelink~' style='color:white;'>~typename~</a></li>";

?>